from pathlib import Path
p=[]
def emit(s):p.append(s)
emit('''# Pure Ethereum Keccak-256 (rate 136 bytes, capacity 512 bits, suffix 0x01).
# Generated by gen_keccak.py: lane index = x + 5*y; each lane is little endian.
# API: hash(+List<U32>) -> W.Word; inputs are masked to bytes.
# Digest bytes form a big-endian integer stored in W.Word little-endian limbs.
import Base
import ../evmword.bend as W

type Lane is Data:
  L{lo: U32, hi: U32}

def xor(a: Lane, b: Lane) -> Lane:
  match a b:
    case L{a, b} L{c, d}:
      L{U32.xor(a, c), U32.xor(b, d)}

def chi(a: Lane, b: Lane, c: Lane) -> Lane:
  match a b c:
    case L{a, b} L{c, d} L{e, f}:
      L{U32.xor(a, U32.and(U32.not(c), e)), U32.xor(b, U32.and(U32.not(d), f))}
''')
rots=[0,1,62,28,27,36,44,6,55,20,3,10,43,25,39,41,45,15,21,8,18,2,61,56,14]
for n in sorted(set(rots+[1])):
 emit(f'def rot{n}(a: Lane) -> Lane:')
 if n==0: emit('  a\n');continue
 lo,hi=('a','b') if n<32 else ('b','a');r=n%32
 emit(f'  match a:\n    case L{{+a, +b}}:\n      L{{U32.or(U32.shln({lo}, {r}n), U32.shrn({hi}, {32-r}n)), U32.or(U32.shln({hi}, {r}n), U32.shrn({lo}, {32-r}n))}}\n')
fields=', '.join(f'a{i}: Lane' for i in range(25)); names=', '.join(f'a{i}' for i in range(25)); pats=', '.join(f'+a{i}' for i in range(25))
emit(f'type State is Data:\n  S{{{fields}}}\n')
emit(f'def round(s: State, rc: Lane) -> State:\n  match s:\n    case S{{{pats}}}:')
for x in range(5):
 terms=[f'a{x+5*y}' for y in range(5)]; e=terms.pop()
 for t in reversed(terms): e=f'xor({t}, {e})'
 emit(f'      +c{x} = {e}')
for x in range(5): emit(f'      +d{x} = xor(c{(x+4)%5}, rot1(c{(x+1)%5}))')
for y in range(5):
 for x in range(5):
  i=x+5*y;j=y+5*((2*x+3*y)%5)
  emit(f'      +b{j} = rot{rots[i]}(xor(a{i}, d{x}))')
out=[]
for y in range(5):
 for x in range(5):
  e=f'chi(b{x+5*y}, b{(x+1)%5+5*y}, b{(x+2)%5+5*y})'
  out.append(f'xor({e}, rc)' if x==y==0 else e)
emit('      S{'+', '.join(out)+'}\n')
rcs=[0x1,0x8082,0x800000000000808a,0x8000000080008000,0x808b,0x80000001,0x8000000080008081,0x8000000000008009,0x8a,0x88,0x80008009,0x8000000a,0x8000808b,0x800000000000008b,0x8000000000008089,0x8000000000008003,0x8000000000008002,0x8000000000000080,0x800a,0x800000008000000a,0x8000000080008081,0x8000000000008080,0x80000001,0x8000000080008008]
emit('def permute(s: State) -> State:')
for i,r in enumerate(rcs):emit(f'  s{i} = round({"s" if i==0 else "s"+str(i-1)}, L{{{r&0xffffffff}, {r>>32}}})')
emit('  s23\n')
emit('''def byte_lane(high: Bool, byte: U32, shift: Nat) -> Lane:
  match high:
    case False{}:
      L{U32.shln(byte, shift), 0}
    case True{}:
      L{0, U32.shln(byte, shift)}
''')
emit('def inject_at(i: U32, s: State, v: Lane) -> State:\n  match i s:')
for i in range(17):
 out=[f'xor(a{j}, v)' if i==j else f'a{j}' for j in range(25)]
 emit(f'    case {i} S{{{names}}}:\n      S{{'+', '.join(out)+'}')
emit('    case _ s:\n      s\n')
emit('''def inject(s: State, +i: U32, byte: U32) -> State:
  inject_at(U32.div(i, 8), s, byte_lane(U32.is_ge(U32.mod(i, 8), 4), U32.and(byte, 255), U32.to_nat(U32.mul(U32.mod(i, 4), 8))))

def advance(full: Bool, s: State) -> State:
  match full:
    case False{}:
      s
    case True{}:
      permute(s)

def absorb(bytes: +List<U32>, s: State, +i: U32) -> State:
  match bytes:
    case Nil{}:
      permute(inject(inject(s, i, 1), 135, 128))
    case Con{b, tail}:
      absorb(tail, advance(U32.is_eq(i, 135), inject(s, i, b)), U32.mod(U32.add(i, 1), 136))

def swap(+x: U32) -> U32:
  U32.or(U32.or(U32.shln(U32.and(x, 255), 24n), U32.shln(U32.and(U32.shrn(x, 8n), 255), 16n)), U32.or(U32.shln(U32.and(U32.shrn(x, 16n), 255), 8n), U32.shrn(x, 24n)))
''')
emit('def digest(s: State) -> W.Word:\n  match s:\n    case S{L{a, b}, L{c, d}, L{e, f}, L{g, h}, '+', '.join('_' for _ in range(21))+'}:\n      W.W{swap(h), swap(g), swap(f), swap(e), swap(d), swap(c), swap(b), swap(a)}\n')
emit('def hash(bytes: +List<U32>) -> W.Word:\n  digest(absorb(bytes, S{'+', '.join('L{0, 0}' for _ in range(25))+'}, 0))\n')
Path(__file__).with_name('keccak.bend').write_text('\n'.join(p))
